version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      REDIS_HOST: ${REDIS_HOST}
      CSV_URL_PATTERN: ${CSV_URL_PATTERN}
    depends_on:
      - redis
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
